title: Project Nimizuela
description: >
  **Project Nimizuela**<br>
  *...raising awareness about*<br>
  ***Nimiq*** *in* ***Venezuela***
copyright: Project Nimizuela
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: "#"
facebook_username: "#"
twitter_username: "#"
linkedin_username:
instagram_username:
pinterest_username:
flickr_username:
github_username:  "#"
dribbble_username:
email: "#"
feed_icon: rss
plugins: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
