title: Project Nimizuela
description: >
  **Project Nimizuela**<br>
  *...raising awareness about*<br>
  ***Nimiq*** *in* ***Venezuela***
copyright: Project Nimizuela
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname:
facebook_username: nimizuela
twitter_username: nimizuela
linkedin_username:
instagram_username:
pinterest_username:
flickr_username:
github_username:  nimizuela
dribbble_username:
discord_server: XtFU7qh
email: nimizuela@protonmail.com
feed_icon: rss
plugins: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
